[project]
name = "expert-estimate"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "MystiSs", email = "vanz.vaf@yandex.ru"},
]
dependencies = ["pandas>=3.0.6"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
# distribution = false

[project.optional-dependencies]
web = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.28.0",
    "python-multipart>=0.0.9",
]

[project.scripts]
expert-estimate = "expert_estimate.algorithm:main"
expert-estimate-web = "api.main:run_server"
